steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "$_IMAGE_NAME:$COMMIT_SHA"
      - .
      - "-f"
      - $_DOCKERFILE_NAME
    dir: $_DOCKERFILE_DIR
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_IMAGE_NAME:$COMMIT_SHA"
    id: Push
images:
  - "$_IMAGE_NAME:$COMMIT_SHA"
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _K8S_ANNOTATIONS: gcb-trigger-id=ab33b6ae-57e8-4ba5-a400-98a54555acf7
  _K8S_APP_NAME: client
  _IMAGE_NAME: gcr.io/tfg-ivo/github.com/ivosequeros/gaze-client
  _OUTPUT_BUCKET_PATH: tfg-ivo_cloudbuild/deploy
  _GKE_CLUSTER: benchmarking-cluster-4
  _K8S_YAML_PATH: kubernetes/definition.yaml
  _DOCKERFILE_NAME: Dockerfile
  _K8S_LABELS: ""
  _K8S_NAMESPACE: default
  _DOCKERFILE_DIR: ""
  _GKE_LOCATION: europe-west3-b
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
timeout: 25m
