apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
  namespace: default
spec:
  replicas: 50
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - image: gcr.io/tfg-ivo/github.com/ivosequeros/gaze-client@sha256:8cbead04f51b6327394bef0a021997300f03bdc698da64cf024185bde115127d
          imagePullPolicy: IfNotPresent
          name: client-sha256-1
          env:
            - name: HOST
              value: 35.198.110.111:6142
      nodeSelector:
        node: client
