apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
  namespace: default
spec:
  replicas: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - image: gcr.io/tfg-ivo/github.com/ivosequeros/gaze-client
          imagePullPolicy: IfNotPresent
          name: client-sha256-1
      nodeSelector:
        node: client
